### ISSUE TITLE
API needs to be updated with new TS version 3.6.0

### ISSUE THREAD

**Issue by ahandinitflo** [MGraefe/RP-Soundboard#118] opened 2023-06-19 19:58 UTC
TS says API is your responsibly. I am assuming it is down for everyone. and FYI all my other plugins are not working in TS so its not just you ...thanks in advance , so I can get to annoying my corp mates with sounds :)

https://i.imgur.com/Icna3h0.png

 
![ts3client_win64_nm7S3GxcrS](https://github.com/MGraefe/RP-Soundboard/assets/47332574/b803fdd8-64c2-4fb2-8773-c5b5cd14623e)

**Comment by KeinNameVorhanden** [comment] 2023-06-19 20:28
Its already updated, check the releases.

[v1.4.2.1819 for Teamspeak 3.6.0 (Windows only)](https://github.com/MGraefe/RP-Soundboard/releases/tag/v1.4.2.1819)

**Comment by MGraefe** [comment] 2023-06-19 20:32
> Its already updated, check the releases.
> 
> [v1.4.2.1819 for Teamspeak 3.6.0 (Windows only)](https://github.com/MGraefe/RP-Soundboard/releases/tag/v1.4.2.1819)

I already uploaded a new version to myTeamspeak on Sunday night, for the auto-update to work. But it needs to manually be approved by Teamspeak staff, no idea how long it will take.

Until then just download the newest release manually.

**Comment by chrisTeamSpeak** [comment] 2023-06-21 12:27
We could not approve the update on myTeamSpeak.
It is on Client API 23. Please ensure the plugin used 26.

**Comment by MGraefe** [comment] 2023-07-01 18:17
@chrisTeamSpeak thanks for notifying me, I changed it to 26. The binaries remain the same as before.

**Comment by chrisTeamSpeak** [comment] 2023-07-06 13:41
Waited some days and now checked our site, but there was no new upload since June 21th.
That one was published as API 23 and was rejected from us.

**Comment by MGraefe** [comment] 2023-07-07 08:21
I don't understand. I uploaded the version thats also in the github release. It clearly works with 3.6.0 and is on API 26.

**Comment by chrisTeamSpeak** [comment] 2023-07-07 09:09
Sure you did, but you did not select API 26 on the website where you uploaded your plugin.  You left it on 23.
So myTS thinks this is API 23 and will only offer the plugin to any 3.5.6 Client with API 23. 
Even then the plugin would not work for them, ebecause API does not match 23.

So when updating a plugin the right API version must be selected.

**Comment by MGraefe** [comment] 2023-07-09 08:42
I forgot to select API 26 the _first_ time, however after your first message I actually selected API 26 and submitted the request again. If it isn't updated properly on your side it's maybe a bug in your system?

Regardless, I now did it again, selected API 26, uploaded the windows binaries again and deleted the old linux binaries. Maybe that'll work, if not them I'm afraid I would need some more help from your side.

**Comment by chrisTeamSpeak** [comment] 2023-07-10 11:21
The upload worked. But your updater causes an error, So the update was rejected. :/

10.07.2023 11:15:10	SB	Error	UpdateChecker: Error requesting version document https://mgraefe.de/rpsb/version/version.xml.
Error-String: Error transferring https://mgraefe.de/rpsb/version/version.xml - server replied: Not Found

**Comment by MGraefe** [comment] 2023-07-10 16:37
Didn't know that a simple error in the client log would be a problem. Should be fixed now, I restored this file on my server.

In general the updater is from a time before myTeamspeak even existed. Nowadays it's not really needed, I would be willing to remove it completely if really necessary, but my time is limited. Just yesterday I spent 5 hours reworking the whole build process and implementing building via github actions with automatic releases. All for an app which is mostly obsolete because of...well...competition and also TS5 on the horizon.

Btw, is Addon support something you consider for Teamspeak 5? What tech stack is TS5 built on anyway? Electron/node.js or is it still Qt under the hood?

**Comment by chrisTeamSpeak** [comment] 2023-07-11 13:49
Imagine every user gets an error on client start. These will contact us because something is broke.
You do not have to remove the updater. You could place the desired file an target location.

TS5 will get plugin support. 
TS5 client is based on Chromium Embedded Framework

**Comment by MGraefe** [comment] 2023-07-12 11:27
Thanks for the feedback. I see that the plugin is updated on myTeamspeak, however if I download the binary, it's still giving me the years old version which is not compatible with API 26. However when I look at the plugin on my dashboard, the addon is shown as approved (no update pending) and the binary is the new one: 
![grafik](https://github.com/MGraefe/RP-Soundboard/assets/8102494/0042e04d-a22d-49cd-a5b4-25456961728c)

So there seems to be a bug in myTeamspeak?

**Comment by chrisTeamSpeak** [comment] 2023-07-12 12:14
Not a bug here. Just me not knowing 100% how to use the panel ;)  Did not do that in the past.

The last upload was rejected because of the updater. Is this fixed? then i can retest if you like and move it out of trash folder.
![grafik](https://github.com/MGraefe/RP-Soundboard/assets/47657175/689030ba-2d41-4afb-ba6e-1cef7a19c3a3)

**Comment by chrisTeamSpeak** [comment] 2023-07-12 19:26
It's approved. Happy sound spamming :D

**Comment by MGraefe** [comment] 2023-07-12 21:43
Thanks!

**Closed by MGraefe** 2023-07-12 21:43 UTC
