### ISSUE TITLE
Soundboard just doesn't work

### ISSUE THREAD

**Issue by bitit0** [MGraefe/RP-Soundboard#54] opened 2017-10-27 01:58 UTC
I've reinstalled ts twice, and the soundboard multiple times. Even the default sounds don't work! I have no idea what to do. Please help! I can provide info/logs/settings/pictures if needed.

**Comment by MGraefe** [comment] 2017-10-27 10:10
I have neither. Seems to be an issue of teamspeak - yet to figure out what happens.

-------- Ursprüngliche Nachricht --------Von: nathngo <notifications@github.com> Datum: 27.10.17  03:58  (GMT+01:00) An: MGraefe/RP-Soundboard <RP-Soundboard@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [MGraefe/RP-Soundboard] Soundboard just doesn't work (#54) 
I've reinstalled ts twice, and the soundboard multiple times. Even the default sounds don't work! I have no idea what to do. Please help! I can provide info/logs/settings/pictures if needed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MGraefe/RP-Soundboard","title":"MGraefe/RP-Soundboard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MGraefe/RP-Soundboard"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Soundboard just doesn't work (#54)"}],"action":{"name":"View Issue","url":"https://github.com/MGraefe/RP-Soundboard/issues/54"}}}

**Comment by MGraefe** [comment] 2018-09-30 16:00
Duplicate of #44

**Closed by MGraefe** 2018-09-30 16:00 UTC
Labels: duplicate
