### ISSUE TITLE
Audio gets often distorted

### ISSUE THREAD

**Issue by MAVREE** [MGraefe/RP-Soundboard#9] opened 2016-09-24 13:27 UTC
Sometimes it happens only with the mic audio, sometimes with the mp3s while the mic sounds perfect and sometimes it happens with everything. A manual fix for the mic distortion is to change output device to another random one, but to fix the soundboard distorted sound I must restart the entire client.

Beside that, the plugin is awesome, props to you!

**Comment by ArthurGiannotta** [comment] 2016-11-17 23:54
I can confirm this problem while building the latest commit up to this point in time. My microphone works normally before playing an audio, but after playing ANY audio file, everything I speak or every audio I sent gets distorted only when inside teamspeak. A manual restart of the client solves the problem. Making an audio test in the Options section, the microphone seems normal, but every person listening to me complains about annoying sounds.

**Comment by MGraefe** [comment] 2016-11-18 01:04
Are you using the Teamspeak 3.1 beta? Because it still has a bug that was confirmed by the devs: http://forum.teamspeak.com/threads/126565-Discussion-TeamSpeak-3-Client-3-1-BETA?p=437972#post437972
I am told this is gonna be fixed in the next beta.

**Comment by GamerMaurizio** [comment] 2016-11-18 14:17
I'm not using TS3 3.1, I've always been using version 3.0.19.4 (Qt Version 5.5.1)

**Comment by WarWolfen** [comment] 2017-01-13 08:08
You could also try to change the codec used in that channel to improve quality. Just a thought.

**Comment by MGraefe** [comment] 2017-06-21 17:46
Newest version fixes distortion issues.

**Closed by MGraefe** 2017-06-21 17:46 UTC
