### ISSUE TITLE
soundbord dosen't work 

### ISSUE THREAD

**Issue by DelfoxPL** [MGraefe/RP-Soundboard#56] opened 2017-11-02 22:34 UTC
I cant play music with Mouse clicking but i can play with bind's and I can't uninstall it.
![image](https://user-images.githubusercontent.com/33333562/32353603-5989eb34-c026-11e7-8001-44a688b95133.png)

**Comment by MGraefe** [comment] 2018-09-30 16:00
Duplicate of #44

**Closed by MGraefe** 2018-09-30 16:00 UTC
Labels: duplicate
