### ISSUE TITLE
Stops playing when I click away from the RP Soundboard window.

### ISSUE THREAD

**Issue by chroniccole** [MGraefe/RP-Soundboard#49] opened 2017-08-24 04:13 UTC
RP soundboard plays just fine, but when I click away from the RP Soundboard window it stops playing the sound file.

**Comment by MGraefe** [comment] 2018-09-30 16:11
Will close this thread since it's over a year old and this is most likely not a bug of the plugin but of Teamspeak or a general issue with the @chroniccole 's Windows.

**Closed by MGraefe** 2018-09-30 16:11 UTC
