### ISSUE TITLE
TS3 voice input cuts out at the end of a sampled sound

### ISSUE THREAD

**Issue by Lokatana** [MGraefe/RP-Soundboard#46] opened 2017-07-28 23:56 UTC
Hi there,

When i play any sound (triggered via a hotkey), it plays great.... but when the sound ends, if i happen to be talking (via push-to-talk), both the sound ends, and my push-to-talk is disabled, leaving me talking into thin air, and people wondering why i suddenly stopped talking.

Any way to prevent it from "stopping" the push to talk when a sound ends?

**Comment by MGraefe** [comment] 2018-09-30 15:51
What version of Teamspeak 3 and the plugin are you using? Because I cannot reproduce this with both up to date (Teamspeak 3.2.2 and RP Soundboard 1.3.5.1733).

**Comment by MGraefe** [comment] 2019-06-16 16:13
Closing: no update in almost two years.

**Closed by MGraefe** 2019-06-16 16:13 UTC
Labels: help wanted
