### ISSUE TITLE
Work great on my computer but on one of my clan member all his sound and voice get distorted.

### ISSUE THREAD

**Issue by Tonyqwater** [MGraefe/RP-Soundboard#11] opened 2016-11-12 02:12 UTC
Thank for this sound board works great on my PC.  But one of my clan member has some issues with it.
he opens teamspeak, all voice is fine but the minute he activate the sound board and plays one sound, the sound plays like if it clipping and kind of robot voice. After when he speaks the voice continues to clip and he also sound like a robot. I have remoted to his PC to investigate, i have found that changing the capture device and setting it back to his default or to his mic fixes the clipping and distortion. If he plays an MP# again, it starts to go wrong again.  He is using the same MP3 as i do.  He has ts version  3.0.19.4 QT 5.5.1 which is the same version as mine. Running win10 and so am I. 

Thanks for the help.

**Comment by MGraefe** [comment] 2016-11-18 01:04
Are you using the Teamspeak 3.1 beta? Because it still has a bug that was confirmed by the devs: http://forum.teamspeak.com/threads/126565-Discussion-TeamSpeak-3-Client-3-1-BETA?p=437972#post437972
I am told this is gonna be fixed in the next beta.

**Comment by Tonyqwater** [comment] 2016-11-19 01:17
No we do not use the Beta, we use 3.0.19.4.

Nicolas Prévost,
Courriel personnel, SVP ne pas envoyé de chaine de courriel.
Personal Email, Please do not send chain mails.

**Comment by MGraefe** [comment] 2016-12-08 10:49
The newest build for Teamspeak 3.1 beta might fix it. http://www.mediafire.com/file/4bdeicgqycsx3da/rp_soundboard_1504.ts3_plugin

**Comment by MGraefe** [comment] 2017-06-21 17:45
Newest version definitely fixes distortion issues.

**Closed by MGraefe** 2017-06-21 17:45 UTC
