### ISSUE TITLE
Can´t start playing sounds with hotkeys

### ISSUE THREAD

**Issue by jumpY21** [MGraefe/RP-Soundboard#61] opened 2018-01-02 13:51 UTC
I am able to start sounds when i click on the button.
But unfortunately, when i assign a hotkey for a specific button and press the hotkey, the sound won´t start.

![chrome_2018-01-02_14-49-59](https://user-images.githubusercontent.com/35033656/34485729-5a708bea-efcc-11e7-91ff-01d88a3ad6b6.png)

**Comment by scitbor** [comment] 2018-01-23 12:49
same here!

**Comment by MGraefe** [comment] 2018-09-30 16:14
Duplicate of #48

**Closed by MGraefe** 2018-09-30 16:14 UTC
